[package]
name = "buyercontract"
version = "0.1.0"
edition = "2023_11"

[dependencies]
starknet = "=2.6.3"
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.12.0" }

[[target.starknet-contract]]
